---
driver:
  name: docker
  # Mac client tries, by default, is setting use_sudo to true  
  # https://github.com/test-kitchen/kitchen-docker/issues/201
  use_sudo: false

driver_config:
  network:
  - ["public_network"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[bcs_java::default]
