---
driver:
  name: docker

driver_config:
  network:
  - ["public_network"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[bcs_java::default]
    attributes:
      java:
        jdk:
          '7':
            x86_64:
              url: "http://10.0.0.33/www/jdk-7u55-linux-x64.tar.gz"

