---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest # passed 14
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[bcs_java::default]
